export function cx(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

export const styles = {
  layout: {
    page: "page",
    pageFull: "page page-full",
    pageStack: "page-stack",
  },
  text: {
    title: "page-title",
    muted: "text-muted",
    soft: "text-soft",
    danger: "text-danger",
    action: "action-link",
  },
  welcome: {
    page: "welcome-page",
    stack: "welcome-stack",
    background: "welcome-background",
    backgroundImage: "welcome-background-image",
    header: "welcome-header",
    titleBox: "welcome-title-box",
    actions: "welcome-actions",
    panel: "welcome-panel",
    prompt: "welcome-prompt text-muted",
    classMeta: "welcome-class-meta",
    heroContent: "welcome-hero-content",
    classLogo: "welcome-class-logo",
    icon: "resource-icon",
    intro: "welcome-intro",
    introTitle: "welcome-intro-title",
    introCopy: "welcome-intro-copy",
    textLink: "welcome-text-link",
    photoBanner: "welcome-photo-banner",
    featureGrid: "welcome-feature-grid",
    featureCard: "welcome-feature-card",
    featureCardLight: "welcome-feature-card welcome-feature-card--light",
    featureImage: "welcome-feature-image",
  },
  classes: {
    page: "classes-page",
    canvas: "classes-canvas",
    hero: "classes-hero",
    intro: "classes-intro",
    introTitle: "classes-intro-title",
    introMain: "classes-intro-main",
    introNotes: "classes-intro-notes",
    schedule: "classes-schedule",
    schedulePanel: "classes-schedule-panel",
    scheduleTitle: "classes-schedule-title",
    scheduleDetails: "classes-schedule-details",
    scheduleNote: "classes-schedule-note",
    scheduleSmall: "classes-schedule-small",
    scheduleImage: "classes-schedule-image",
  },
  faqs: {
    page: "faqs-page",
    canvas: "faqs-canvas",
    hero: "faqs-hero",
    intro: "faqs-intro",
    introTitle: "faqs-intro-title",
    stack: "faqs-stack",
  },
  about: {
    page: "about-page",
    stack: "about-stack",
    hero: "about-hero",
    intro: "about-intro",
    title: "about-title",
    introMain: "about-intro-main",
    introNotes: "about-intro-notes",
    people: "about-people",
    peoplePanel: "about-people-panel",
    peopleDetails: "about-people-details",
    peopleNote: "about-people-note",
    peopleSmall: "about-people-small",
    peopleImage: "about-people-image",
    peopleCarousel: "people-carousel-container",
    peopleTrack: "people-carousel-track",
    peopleCard: "people-carousel-card",
    peopleCardImage: "people-card-image",
    peopleCardBody: "people-card-body",
    peopleCardRole: "people-card-role",
    peopleCardName: "people-card-name",
    peopleCardBio: "people-card-bio",
  },
  join: {
    banner: "join-banner",
    track: "join-track",
    group: "join-group",
  },
  footer: {
    footer: "footer",
    logo: "footer-logo",
    content: "footer-content",
    links: "footer-links",
    venue: "footer-venue",
    social: "footer-social",
  },
  button: {
    primary: "primary-button",
    primarySmall: "primary-button primary-button-small",
  },
  nav: {
    shell: "app-nav",
    header: "app-nav-header",
    brand: "app-nav-brand",
    compactLogo: "app-nav-logo app-nav-logo--compact",
    fullLogo: "app-nav-logo app-nav-logo--full",
    desktopLinks: "app-nav-desktop-links",
    link: "app-nav-link",
    desktopActions: "app-nav-desktop-actions",
    menuButton: "app-nav-menu-button",
    backdrop: "app-nav-backdrop",
    drawer: "app-nav-drawer",
    drawerLogo: "app-nav-drawer-logo",
    drawerLinks: "app-nav-drawer-links",
    drawerActions: "app-nav-drawer-actions",
  },
  booking: {
    page: "booking-page",
    heading: "booking-h1",
    sub: "booking-sub",
    shell: "booking",
    tabs: {
      nav: "booking-tabs-nav",
      tabOn: "booking-tabs-tab booking-tabs-tab--on",
      tab: "booking-tabs-tab",
    },
    grid: {
      locked: "booking-grid booking-grid-locked",
      normal: "booking-grid",
    },
    card: {
      locked: "booking-card booking-card--locked",
      selected: "booking-card booking-card--on",
      normal: "booking-card",
      mo: "booking-card-mo",
      day: "booking-card-day",
    },
    cta: {
      base: "booking-cta",
      dim: "booking-cta booking-cta--dim",
      withGap: "booking-cta booking-cta--top-gap",
    },
    modal: {},
  },
  feedback: {
    overlay: "feedback-overlay",
    dialog: "feedback-dialog",
    icon: "feedback-icon",
    heading: "feedback-heading",
    body: "feedback-body",
    actions: "feedback-actions",
    action: "feedback-action",
    close: "feedback-close",
  },
  panel: {
    bordered: "panel",
  },
  auth: {
    overlay: "auth-overlay",
    dialog: "auth-dialog",
    closeButton: "auth-close-button",
    title: "auth-title",
    intro: "auth-intro",
    form: "auth-form",
    copy: "auth-copy",
    mutedCopy: "auth-copy-muted",
    input: "auth-input",
    inputRequired: "auth-input-required",
    inputWithAction: "auth-input-with-action",
    requiredMark: "auth-required-mark",
    requiredAtEnd: "auth-required-mark-end",
    requiredWithAction: "auth-required-mark-with-action",
    link: "auth-link",
    forgotLink: "auth-forgot-link",
    accessLabel: "auth-access-label",
    accessCopy: "auth-access-copy",
    accessInput: "auth-input auth-access-input",
    ageLabel: "auth-age-label",
    ageCopy: "auth-age-copy",
    ageInput: "auth-input auth-age-input",
    error: "auth-error",
    submit: "auth-submit",
    footer: "auth-footer",
    footerButton: "auth-footer-button",
    field: "auth-field",
    fieldControl: "auth-field-control",
    passwordToggle: "auth-password-toggle",
    oauthHeader:  "auth-oauth-header",
    oauthButtons: "auth-oauth-buttons",
    oauthButton: "auth-oauth-button",
    divider: "auth-divider",
    dividerText: "auth-divider-text",
  },
  members: {
    page:  "members-page",
    header:  "members-header",
    grid: "members-grid",
    rightCol: "members-right-col",
    eyebrow: "members-eyebrow",
    name: "members-name",
    email: "members-email",
    card: "members-card",
    cardTitle: "members-card-title",
    cardSubtitle: "members-card-subtitle",
    cardNote: "members-card-note",
    sectionLabel: "members-section-label",
    empty: "members-empty",
    fieldList: "members-field-list",
    field: "members-field",
    fieldLabel: "members-field-label",
    fieldValue: "members-field-value",
    fieldInput: "members-field-input",
    checkboxRow: "members-checkbox-row",
    checkboxWrap: "members-checkbox-wrap",
    checkbox: "members-checkbox",
    checkboxIndicator: "members-checkbox-indicator",
    checkboxCheckedWithMembersCheckboxIndicator: "members-checkbox:checked + .members-checkbox-indicator",
    checkboxLabel: "members-checkbox-label",
    textarea: "members-textarea",
    saveButton: "members-save-button",
    link: "members-link",
    bookingsGrid: "members-bookings-grid",
    bookingCard: "members-booking-card",
    bookingMonth: "members-booking-month",
    bookingDay: "members-booking-day",
    bookingMove: "members-booking-move",
    membershipList: "members-membership-list",
    membershipItem: "members-membership-item",
    membershipRenews: "members-membership-renews",
  },
  user: {
    menu: "user-menu",
    menuTrigger: "user-menu-trigger",
    menuAvatar: "user-menu-avatar",
    menuInitials: "user-menu-initials",
    menuDropdown: "user-menu-dropdown",
    menuInfo: "user-menu-info",
    menuInfoName: "user-menu-info-name",
    menuInfoEmail: "user-menu-info-email",
    menuDivider: "user-menu-divider",
    menuItem: "user-menu-item",
  }
} as const;
